baseURL = 'https://www.yjmrobert.com/itamae/'
relativeURLs = true
languageCode = 'en-us'
title = 'Itamae'
theme = 'hugo.386'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[params]
    mainpagetitle = "Itamae"
    mainpagesubtitle = "A command-line tool to set up a developer's Linux workstation."
    mainpagedesc = "Itamae is a command-line tool designed to automate the setup of your Linux workstation. It handles dotfiles, packages, and configuration with ease."

    copyrightname = "Itamae Contributors"
    copyrighturl = "https://github.com/yjmrobert/itamae"

    showhugo = true

    github = "https://github.com/yjmrobert/itamae"

    loadfastload = false

[params.copyright]
    name = "Itamae Contributors"
    url = "https://github.com/yjmrobert/itamae"
    prefix = "Itamae"
    suffix = "Documentation"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    pageRef = "/docs"
    weight = 1

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/yjmrobert/itamae"
    weight = 2
