baseURL = '/'
languageCode = 'en-us'
title = 'Itamae Documentation'
theme = 'hugo-theme-relearn'

[outputs]
home = ['HTML', 'RSS']

[params]
  # Relearn theme options
  disableNextPrev = true
  disableLandingPage = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = true
  
  # Theme variant - subtle Tokyo Night dark theme
  themeVariant = 'relearn-dark'
  
  # Description for SEO
  description = 'Itamae - A command-line tool for setting up Linux development workstations'
  
  # Author
  author = 'yjmrobert'
  
  # Show breadcrumbs
  showVisitedLinks = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = 'monokai'
    tabWidth = 4
